### PR TITLE
Accessibility improvement

### PR DESCRIPTION
**Pull request by eserkansozer**
To make the icon selectable and readable by screen readers.

### CODE REVIEW

**Comment by frankieroberto** [comment]
@eserkansozer hello! Thanks so much for suggesting this accessibility improvement.

Could you explain a bit more about the rationale for this change?  My assumption was that the icon didn't need to be clickable or readable by screen readers, as the whole header area is clickable and readable, so the icon would just be duplicate information?

**Comment by eserkansozer** [comment]
When you use keyboard tab key, the accordion header did not focus therefore was not possible to expand it only with keyboard.
At least, it did not in my solution. Here is how it works now: (https://as-t1dv-sfb.azurewebsites.net/BenchmarkCriteria/AdvancedCharacteristics?areaType=All&lacode=&lanametext=&Urn=134989&ComparisonType=Advanced&EstType=All)

**Comment by frankieroberto** [comment]
@eserkansozer ah ok, I can repeat this in Chrome too. 

So I think a better fix is to make sure that the header is tabbable, rather than the icon, although I'm not sure whether it should be the whole header section – "General characteristics (0 selected)" in your example – or just the main label ("General characteristics").

On the GOV.UK Service Manual, this is achieved by using a `<button>` element for the header, instead of an `h2`: https://www.gov.uk/service-manual/helping-people-to-use-your-service – have you tried that?

**Comment by eserkansozer** [comment]
Yes I saw it now. That’s another way of doing it. But that way it is not as intuitive what that header(button) is doing (open/collapse). That can of course can be improved with aria-labels for screen readers but still I think the header is not meant to be the button, icon is.

Anyway accessibility of the accordions have potential to be improved. Please feel free to implement what you like best.

Serkan

**Comment by frankieroberto** [comment]
@eserkansozer hi again. Thanks again for bringing this to my attention.

I've opened another pull request: #2 which attempts to improve keyboard accessibility by allowing the whole header section to be focusable and to respond to key presses. Let me know what you think. I'm going to try and do a bit more testing too.

**Comment by frankieroberto** [comment]
Closing this in favour of #2 which makes the whole section header toggleable with the keyboard instead.

**Pull request closed without merging**
